# Generated by Django 5.2.4 on 2025-08-03 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_novel', '0003_novel_word_num_alter_novel_linked'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginalWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='原作名')),
                ('author', models.CharField(blank=True, max_length=50, verbose_name='原作者')),
                ('description', models.TextField(blank=True, verbose_name='原作の説明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': '原作',
                'verbose_name_plural': '原作一覧',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='タグ名')),
                ('description', models.TextField(blank=True, verbose_name='タグの説明')),
                ('color', models.CharField(default='#3498db', max_length=7, verbose_name='表示色')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': 'タグ',
                'verbose_name_plural': 'タグ一覧',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='novel',
            options={'ordering': ['-created_at'], 'verbose_name': '小説', 'verbose_name_plural': '小説一覧'},
        ),
        migrations.AddField(
            model_name='novel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='登録日時'),
        ),
        migrations.AddField(
            model_name='novel',
            name='summary',
            field=models.TextField(blank=True, verbose_name='あらすじ（新）'),
        ),
        migrations.AddField(
            model_name='novel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新日時'),
        ),
        migrations.AddField(
            model_name='novel',
            name='word_count',
            field=models.PositiveIntegerField(blank=True, help_text='半角数字で入力', null=True, verbose_name='文字数（新）'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='linked',
            field=models.URLField(verbose_name='小説のURL'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='summry',
            field=models.TextField(verbose_name='あらすじ（従来）'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='tag',
            field=models.TextField(verbose_name='タグ（従来）'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='title',
            field=models.CharField(max_length=100, verbose_name='タイトル'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='word_num',
            field=models.TextField(null=True, verbose_name='文字数（従来）'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='work_name',
            field=models.CharField(max_length=50, verbose_name='原作名（従来）'),
        ),
        migrations.AddField(
            model_name='novel',
            name='original_work',
            field=models.ForeignKey(blank=True, help_text='この小説の原作を選択してください', null=True, on_delete=django.db.models.deletion.CASCADE, to='web_novel.originalwork', verbose_name='原作'),
        ),
        migrations.AddField(
            model_name='novel',
            name='tags',
            field=models.ManyToManyField(blank=True, help_text='この小説に適用するタグを選択してください', to='web_novel.tag', verbose_name='タグ'),
        ),
    ]
