# Generated by Django 5.2.4 on 2025-08-03 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_novel', '0004_originalwork_tag_alter_novel_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='summry',
            field=models.TextField(blank=True, default='', verbose_name='あらすじ（従来）'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='tag',
            field=models.TextField(blank=True, default='', verbose_name='タグ（従来）'),
        ),
        migrations.AlterField(
            model_name='novel',
            name='work_name',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='原作名（従来）'),
        ),
    ]
